[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "py_turbo"
version = "0.3.0"
dependencies = []
requires-python = ">=3.7"

[tool.isort]
profile = "black"

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@overload"]