name: CD

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  windowsbuid:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            ./target/x86_64-pc-windows-gnu/release/turbo.exe

  linuxbuild:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.57.0
          override: true
      - run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            ./target/release/turbo

  macbuid:
    name: Mac Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          override: true
      - run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: mac
          path: |
            ./target/release/turbo
