name: python-release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  universal-macos-release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-latest" ]
        python-version: [ "3.7" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          override: true
          components: rustfmt, clippy
      - name: Setup universal2 targets for Rust
        run: |
          rustup target add aarch64-apple-darwin
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: maturin publish
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          maturin-version: 0.12.1
          command: publish
          args: -m turbo-py/Cargo.toml --target aarch64-apple-darwin --no-sdist -o wheels -i python -u benjaminjellis
