name: turbolib-release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always


jobs:

  turbolib-release:
    name: turbolib release
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.57.0
          override: true
      - run: cargo publish -p turbolib
